steps:
  # Step 0: Log in, build, and push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "$$DOCKERHUB_PASSWORD" | docker login -u "$$DOCKERHUB_USERNAME" --password-stdin
        docker build -t sahil161/patel-flaskapp-assign2:latest .
        docker push sahil161l/patel-flaskapp-assign2:latest
    secretEnv: ['DOCKERHUB_USERNAME', 'DOCKERHUB_PASSWORD']

  # Step 1: Reset the instance to pull the latest image
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:516.0.0-slim'
    args:
      - compute
      - instances
      - reset
      - patel-flask-instance
      - --zone=us-central1-a

# Specify logging option and machine type
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Reference the secrets
availableSecrets:
  secretManager:
    - versionName: projects/terra-453319/secrets/dockerhub-username/versions/latest
      env: DOCKERHUB_USERNAME
    - versionName: projects/terra-453319/secrets/dockerhub-password/versions/latest
      env: DOCKERHUB_PASSWORD
