steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'sahil161/patel-flaskapp-assign2:latest', '.']
  # Push the image to Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'sahil161/patel-flaskapp-assign2:latest']
  # Restart the container on the instance
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - '-c'
      - |
        gcloud compute ssh sahil161-flask-instance --zone us-central1-a --command "docker stop \$(docker ps -q) && docker run -d -p 5000:5000 sahil161/patel-flaskapp-assign2:latest"
    entrypoint: 'bash'
